name: stock-advisor
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - pip:
    - transformers>=4.35.0
    - peft>=0.6.0
    - accelerate>=0.22.0
    - bitsandbytes>=0.41.0
    - datasets>=2.14.0
    - wandb>=0.15.0
    - sentencepiece>=0.1.99
    - protobuf>=4.23.0
    - scikit-learn>=1.2.0
    - yfinance>=0.2.28
    - requests>=2.31.0
    - tqdm>=4.66.0
    - scipy>=1.11.0
    - seaborn>=0.12.0
    - jsonlines>=3.1.0
    - einops>=0.6.0 
